services:
  db:
    image: postgres:17-alpine
    container_name: gopherdrop_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gopherdropdb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gopherdropdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gopherdrop

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    container_name: gopherdrop_app
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: gopherdropdb
      DB_SSLMODE: disable
      SECRET_KEY: supersecretkeysupersecretkey32
      LISTEN_ADDR: :8080
      STORAGE_PATH: /app/storage
      MAX_FILE_SIZE: 10485760
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:80"
    networks:
      - gopherdrop

networks:
  gopherdrop:
    driver: bridge

volumes:
  db_data: {}
